# input configuraiton 
fields:
  - id: splunk_hec_server
    type: string
    label: Splunk HEC Server
  - id: splunk_hec_port
    type: string
    label: Splunk HEC Port
  - id: splunk_hec_token
    type: string
    label: Splunk HEC Token
    secret: true
required:
  - splunk_hec_server
  - splunk_hec_port
  - splunk_hec_token

# injector configuration
env:
  SPLUNK_URL: >-
    https://{{ splunk_hec_server }}:{{ splunk_hec_port
    }}/services/collector/event
  SPLUNK_HEC_PORT: '{{ splunk_hec_port }}'
  SPLUNK_AUTHTOKEN: '{{ splunk_hec_token }}'
  SPLUNK_HEC_TOKEN: '{{ splunk_hec_token }}'
  SPLUNK_HEC_SERVER: '{{ splunk_hec_server }}'

